// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB0LNE1EiYs51ULKMtCFLbPIGj4brX-xPo',
    appId: '1:32268977363:web:0b62507eb8e0abba660026',
    messagingSenderId: '32268977363',
    projectId: 'chat-app-fa87a',
    authDomain: 'chat-app-fa87a.firebaseapp.com',
    storageBucket: 'chat-app-fa87a.appspot.com',
    measurementId: 'G-XEMX08J8J2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBku-4UiAFmqERWzANIYnURKIxxQvoRHwY',
    appId: '1:32268977363:android:634400dea4557d60660026',
    messagingSenderId: '32268977363',
    projectId: 'chat-app-fa87a',
    storageBucket: 'chat-app-fa87a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA5awCegY2pBFQNPe9V75LKsFP5XFKQDrM',
    appId: '1:32268977363:ios:1b1c8f4d0d51e9d6660026',
    messagingSenderId: '32268977363',
    projectId: 'chat-app-fa87a',
    storageBucket: 'chat-app-fa87a.appspot.com',
    iosBundleId: 'com.example.chat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA5awCegY2pBFQNPe9V75LKsFP5XFKQDrM',
    appId: '1:32268977363:ios:1b1c8f4d0d51e9d6660026',
    messagingSenderId: '32268977363',
    projectId: 'chat-app-fa87a',
    storageBucket: 'chat-app-fa87a.appspot.com',
    iosBundleId: 'com.example.chat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB0LNE1EiYs51ULKMtCFLbPIGj4brX-xPo',
    appId: '1:32268977363:web:5c34c08342751438660026',
    messagingSenderId: '32268977363',
    projectId: 'chat-app-fa87a',
    authDomain: 'chat-app-fa87a.firebaseapp.com',
    storageBucket: 'chat-app-fa87a.appspot.com',
    measurementId: 'G-MKLQM1BRW4',
  );
}
